#!/bin/bash

latest_backup=$(ls "$HOME" | grep -E "^Backup-[[:digit:]]{2}-[[:digit:]]{2}-[[:digit:]]{2}$" | sort | tail -n1)

if [ ! -e "$HOME/backup-report" ]
then
	touch "$HOME/backup-report"
fi

cur_date=$(date +"%y-%m-%d")
cur_date_sec=$(date -d "$cur_date" +"%s")
backup_date=$(echo "$latest_backup" | sed "s/Backup-//")
backup_date_sec=$(date -d "$backup_date" +"%s")

dif=$(echo "(${cur_date_sec} - ${backup_date_sec}) / (24 * 3600)" | bc)

if [ "$dif" -ge "7" ] || [ -z "$latest_backup" ]
then
	mkdir "$HOME/Backup-${cur_date}"
	for line in $(ls "$HOME/source")
	do
		cp "$HOME/source/$line" "$HOME/Backup-${cur_date}"
	done
	echo -e "--Create $HOME/Backup-${cur_date}\n-Created files:\n$(ls "$HOME/source")" >> "$HOME/backup-report"
else
	touch .update.lst
	touch .create.lst

	for line in $(ls "$HOME/source")
	do
		if [ ! -f "$HOME/$latest_backup/$line" ]
		then
			cp "$HOME/source/$line" "$HOME/$latest_backup"
			echo "$line" >> .create.lst
		else
			size=$(wc -c "$HOME/$latest_backup/$line" | awk '{print $1}')
			size_update=$(wc -c "$HOME/source/$line" | awk '{print $1}')

			if [ "$size" -ne "$size_update" ]
			then
				mv "$HOME/$latest_backup/$line" "$HOME/$latest_backup/$line.${cur_date}"
				echo "$line $line.${cur_date}" >> .update.lst
				cp "$HOME/source/$line" "$HOME/$latest_backup/"
			fi
		fi
	done

	echo -e "\n--Update $backup $cur_date" >> "$HOME/backup-report"
	if [ ! -s ".create.lst" ] && [ ! -s ".update.lst" ]
	then
		echo "No file updates" >> "$HOME/backup-report"
	else
		if [ -s ".create.lst" ]
		then
			echo -e "-Created files:\n$(cat .create.lst)" >> "$HOME/backup-report"
		fi

		if [ -s ".update.lst" ]
		then
			echo -e "-Updated files:\n$(cat .update.lst)" >> "$HOME/backup-report"
		fi
	fi

	rm -rf .update.lst
	rm -rf .create.lst
fi
