#!/bin/bash

declare -A start
declare -A delta
declare -A cmd

timelimit="60"

while [[ "$SECONDS" -le "$timelimit" ]]
do
	for pid in $(ps axu | awk '{print $2}')
	do
		if [[ "$pid" -ne "$$" ]]
		then
			if [[ "${start[$pid]}" -eq "" ]]
			then
				if [[ -r /proc/$pid/io ]]
				then
					delta[$pid]="0"
					start[$pid]=$(grep "rchar" /proc/$pid/io | awk '{print $2}')
					cmd[$pid]=$(cat /proc/$pid/cmdline | tr -d '\0')
				fi
			else
				let delta[$pid]=$(grep "rchar" /proc/$pid/io | awk '{print $2}')-${start[$pid]}
			fi
		fi
	done
	echo -n -e "In progres: $SECONDS / $timelimit\r"
done
echo "$(
for pid in "${!delta[@]}"
do
	echo "$pid ${delta[$pid]} ${cmd[$pid]}"
done)" | sort -k2 -n -r | head -n3 | awk '{print $1" : "$2" : "$3}'
