#!/bin/bash

while true
do
	read input
	echo "$input" > pipe

	if [[ "$input" == "QUIT" ]]
	then
		exit 0
	fi

	if [[ "$input" != "+" && "$input" != "*" && "$input" != [0-9]* ]]
	then
		exit 1
	fi
done
